### ISSUE TITLE
jsonnet.previewToSide not working

### ISSUE THREAD

**Issue by bobelev** [rakam-io/vscode-rakam#4]
```
Error: Could not render Jsonnet; Error: command 'vscode.previewHtml' not found
```

Looks like it's already deprecated https://github.com/microsoft/vscode/issues/62630

**Comment by buremba** [comment]
Hey @bobelev, that's correct. We switched from VSCode extension to an embedded IDE on app.rakam.io so this extension is not maintained anymore.

**Comment by buremba** [comment]
I'm going to archive the repository now.
